### ISSUE TITLE
Problem in 'show seconds'

### ISSUE THREAD

**Issue by AraafRoyall** [Xposed-Modules-Repo/org.strawing.customiuizermod#3]
Now in last update show seconds are working , but they are visible after AM/PM option for example time shown is : 6:30 AM:20  ... means seconds are showing after AM and PM not with time ...

**Comment by liyafe1997** [comment]
Got it... I was not consider about th 12 hour format...

Let me find a way to fix it.

**Comment by araafroyall** [comment]
Ok we are waiting ....

**Comment by AraafRoyall** [comment]
What happened developer, we are still waiting for a long time
