### ISSUE TITLE
Hide status bar icons does not work

### ISSUE THREAD

**Issue by FinaFina233** [Xposed-Modules-Repo/org.strawing.customiuizermod#4]
![Screenshot_2022-05-31-04-17-19-648_org.strawing.customiuizermod.jpg](https://user-images.githubusercontent.com/52440333/171055068-e756d2fc-9f88-4071-adc9-00f8cd4bffb8.jpg) i was trying to hide the alarm headset and muted icon, which does not work for me.
and no network speed separater does not work either.
(btw thanks for fixing the music visualizer, I was not giving hope to that actually, so again thanks a lot.

**Comment by liyafe1997** [comment]
What is your Android and MIUI version? Could you submit the LSPosed log and also your SystemUI.apk if you know how to do that?

**Comment by FinaFina233** [comment]
I'm on Android 11 MIUI12.5.6.0(RFACNXM)
[LSPosed_2022-05-31T11_04_50.438.zip](https://github.com/Xposed-Modules-Repo/org.strawing.customiuizermod/files/8801918/LSPosed_2022-05-31T11_04_50.438.zip)
i'm facing trouble uploading the apk, it says "is not included in the list", i couldnt find the solution, so imma send a onedrive link https://1drv.ms/u/s!AsN3MiZRsg3siDH2DAXHv5rv-Bbt?e=CCL6ZX

**Comment by FinaFina233** [comment]
> What is your Android and MIUI version? Could you submit the LSPosed log and also your SystemUI.apk if you know how to do that?

![IMG_20220601_225325.jpg](https://user-images.githubusercontent.com/52440333/171434474-016c9e56-96ca-4b31-b9f7-decbaad17a3d.jpg)
just to mention the show second does not
seem to display properly on the notification drawer either
